### ISSUE TITLE
CLI for multsig contract | Bounty: TBD

### ISSUE THREAD

**Issue by ilblackdragon** [near/bounties#10]
# Description
A CLI tool `near-multisig` that would allow users to deploy mutisig contract, create requests, view them and confirm.

## Context
https://github.com/near/core-contracts/tree/master/multisig#usage

# Acceptance
* [ ] Can deploy new multisig contract
* [ ] Can view current requests in a nice text UI
* [ ] Create request to send funds, call functions, etc
* [ ] Confirm existing requests
* [ ] Works with Ledger (for example similar to near-shell via --useLedgerKey flag)

# Bounty
TBD $NEAR

**Comment by mattlockyer** [comment]
This bounty should be built on/after [Extend create-near-app to create CLI tools for smart contracts #11](https://github.com/near/bounties/issues/11)

**Comment by ilblackdragon** [comment]
Closing this, because we are going to build multisig support into near-cli
