### ISSUE TITLE
Idea bank | Bounty: $500 USD in NEAR

### ISSUE THREAD

**Issue by ilblackdragon** [near/bounties#12]
# Description
An app, where people can post their ideas.

## Context
The benefit of the idea bank on blockchain:
 * No patent trolling is possible, as one can prove the idea was posted prior
 * Ideas are public and allow developers and entrepreneurs to jump on them
 * Can add voting to upvote ideas
 * Can add linking to projects that actually do this idea - both helps people discover cool stuff & shortcut research for entrepreneur that thinks to work on this idea
 * If becomes popular - can later add fund raising or whatever other components

There is a similar app for stackoverflow that can be used an example: https://github.com/khorolets/nearoverflow-demo

# Acceptance
* [x] Is deployed on TestNet and there is public webpage for everyone to access it
* [x] Source code is on Github 
* [x] Anyone can go and send an idea, that gets checked in on the blockchain
* [x] Anyone can view the list of ideas from blockchain
* [x] Anyone can upvote the idea (depositing 1 N), recording in the smart contract

# Bounty
USD $500 in NEAR

**Comment by djuanit0x** [comment]
I am going to start working on this.

**Comment by luciotato** [comment]
@djuanit0x are you still working on this? I would like to take a shot at this

**Comment by djuanit0x** [comment]
Yes, I started a while ago but still working on it.

**Comment by ilblackdragon** [comment]
@djuanit0x wanted to check on the status?

I'm going to switch this to a competition given @luciotato is also interested.
Specifically, whoever provides a solution that matches acceptance criteria will get the bounty.
To submit your solution (and provide timestamp) - please leave a comment here with link to the github & webpage.

**Comment by djuanit0x** [comment]
Hi, thanks for reaching me out.
I am still currently working out for at least making the website look prettier. Otherwise, I think I have managed to fulfill the acceptance  criteria. I also would like to request your feedback if you mind and anything that I can fix or improve on the project. 

Project link on Github --> https://github.com/djuanit0x/nearideas
Webpage --> https://djuanit0x.github.io/nearideas

Thank you.

**Comment by sima2607** [comment]
Hi, tell me how much time is left until the end
Idea bank | Bounty. I have an idea, but is it worth starting or is it too late?

**Comment by Yolotron** [comment]
> Hi, thanks for reaching me out.
> I am still currently working out for at least making the website look prettier. Otherwise, I think I have managed to fulfill the acceptance criteria. I also would like to request your feedback if you mind and anything that I can fix or improve on the project.
> 
> Project link on Github --> https://github.com/djuanit0x/nearideas
> Webpage --> https://djuanit0x.github.io/nearideas
> 
> Thank you.

Hi man, I was testing it out.
I missed the option to delete my Idea.
I missed the box to add a small description. 
and seems the idea just publish if I vote, other wise the transaction does not pup up
Besides, feels good :D

**Comment by cameron-NEAR** [comment]
Is this bounty completed and paid? If so, can I close it? @ilblackdragon 

I'm asking this to identify which bounties are currently active so I can find people to complete them.

**Comment by ilblackdragon** [comment]
@djuanit0x I actually don't remember what's the status here, can you please remind?

**Comment by djuanit0x** [comment]
If I remember correctly, I think I have fulfilled the acceptance requirements. I'm waiting for the review and feedback.

**Comment by cameron-NEAR** [comment]
Hi @djuanit0x! Your submission has been approved! Please complete this form so we can pay you ASAP :) -  

https://docs.google.com/forms/d/e/1FAIpQLSe2zE_tOocACxBZwNgHUVEfwBmxA6Enas4uVlFoV0nCgsXQGQ/viewform
