### ISSUE TITLE
Improve Validators page in Explorer | Bounty: $500 USD in NEAR

### ISSUE THREAD

**Issue by ilblackdragon** [near/bounties#14]
# Description
Current validators page doesn't provide much information

## Context
There is an issue that outline specifics: https://github.com/near/near-explorer/issues/339

# Acceptance Criteria
* [ ] Validators page in explorer shows all information that `near validators` and `near proposals` commands have augmented with telemetry information

# Bounty
USD $500 in NEAR

**Comment by PfanP** [comment]
@ilblackdragon Would you assign it to me?

**Comment by icerove** [comment]
We already rework node page for validating table and add proposal table. and only some indicators like seat price and epoch process and block average time information left to implementation.
Also, for what information we would show on table, need comments from @frol and maybe also need design for that.
@frol

**Comment by frol** [comment]
I think we should close this bounty and start a new one with more details if needed. As @icerove pointed out, the main implementation is done and the only changes we need to implement are blocked on design and some fine details.
