### ISSUE TITLE
Add Vue template to create-near-app | Bounty: 1600 NEAR

### ISSUE THREAD

**Issue by chadoh** [near/bounties#17]
# Description

Add new template to `create-near-app` allowing people to quickly initialize a Vue project integrated with NEAR

## Context

At the time of writing, https://github.com/near/create-near-app only has two frontend templates:

* vanilla JavaScript
* React

These aren't for everyone, and NEAR itself has no such limitation. It would be awesome to have a template to help people get quickly started building a new NEAR+Vue app.

# Acceptance Criteria

* [ ] new template in `templates/vue`
* [ ] uses same `global.css` & design as vanilla & react templates
* [ ] can use `assemblyscript` (default) and `rust` contract (modify the `if (contract === 'rust')` block in `index.js` if necessary)
* [ ] has proper symlinks for rapid local development, as were added to vanilla & react templates in https://github.com/near/create-near-app/pull/386
* [ ] corresponding updates to `.dependabot/config.yml`
* [ ] corresponding updates to `test/test-new-project.js` & `.travis.yml`

# Bounty
Bounty: [1600Ⓝ]

**Comment by developerfred** [comment]
Is it still open? @chadoh

**Comment by chadoh** [comment]
@developerfred all yours!

**Comment by chadoh** [comment]
@developerfred you may want to start off branching from https://github.com/near/create-near-app/pull/420 and then rebase on `master` once it gets merged

**Comment by developerfred** [comment]
@chadoh perfect, thanks!

**Comment by chadoh** [comment]
Any updates, @developerfred ?

**Comment by luciotato** [comment]
@chadoh It's OK if I take a shot at this?

**Comment by chadoh** [comment]
@luciotato: Given that we haven't had any update from @developerfred i think it's safe to go for it. @developerfred please let us know if you're still working on this and if you expect to wrap it up soon.

**Comment by faragly** [comment]
@chadoh would you like to get a similar template for angular? I would love to start creating it.

**Comment by luciotato** [comment]
@chadoh thanks! I advanced up-to 90% yesterday: I've created a vue3 new project with `vue create` then added the NEAR integration & equivalent front-end from the react & vanilla templates. I've tested it on a clean machine and it's working flawlessly. The repo is at https://github.com/luciotato/NEAR-Vue-example

Now I'm gonna integrate that into a template for `create-near-app`

**Comment by chadoh** [comment]
@faragly I've created a bounty for Angular, #24. Let's discuss it over there!

**Comment by luciotato** [comment]
@chadoh Let's merge https://github.com/near/create-near-app/pull/452
