### ISSUE TITLE
Add Angular template to create-near-app | Bounty: 1600 NEAR

### ISSUE THREAD

**Issue by chadoh** [near/bounties#24]
# Description

Add new template to `create-near-app` allowing people to quickly initialize a Angular project integrated with NEAR

## Context

At the time of writing, https://github.com/near/create-near-app only has two frontend templates:

* vanilla JavaScript
* React

These aren't for everyone, and NEAR itself has no such limitation. It would be awesome to have a template to help people get quickly started building a new NEAR+Angular app.

# Acceptance Criteria

* [x] new template in `templates/angular`
* [x] uses same `global.css` & design as vanilla & react templates
* [ ] can use `assemblyscript` (default) and `rust` contract (modify the `if (contract === 'rust')` block in `index.js` if necessary)
* [ ] has proper symlinks for rapid local development, as were added to vanilla & react templates in https://github.com/near/create-near-app/pull/386
* [ ] corresponding updates to `.dependabot/config.yml`
* [ ] corresponding updates to `test/test-new-project.js` & `.travis.yml`

# Bounty
Bounty: [1600Ⓝ]

**Comment by faragly** [comment]
I start developing a template

**Comment by chadoh** [comment]
Thanks, @faragly! Looking forward to hearing an update about it soon. Let me know if you run into any problems or have any questions.

**Comment by Hugoo** [comment]
Is it possible to also take this bounty or it is only one "user" at a time?

**Comment by chadoh** [comment]
@Hugoo we only need it implemented once, so let's give @faragly some time to work on it before creating a situation where we are not sure who to give the bounty to

**Comment by faragly** [comment]
@chadoh I almost finished developing the template, in the process there were some problems, I will have to move the `config.js` file to the template directory. Angular does not allow access to environment variables in the application, so when deploying the contract, I will write a file with the exportable constant `CONTRACT_NAME`. I hope this won't be a problem.

**Comment by chadoh** [comment]
@faragly that sounds great! The same thing that happened when creating the Vue template: https://github.com/near/create-near-app/pull/452#discussion_r472564404, so there might be a small conflict there. Please create a draft PR and we can discuss more there.

**Comment by chadoh** [comment]
@faragly near/create-near-app#457 moved `config.js` to each individual template directory, deleting the file from `common/frontend`

**Comment by faragly** [comment]
@chadoh all that remains is to migrate [from TSLint to ESLint](https://github.com/angular/angular-cli/issues/13732) and I'll be ready to create PR.

**Comment by chadoh** [comment]
You can create a draft PR to work in the open, show progress, and have conversations about it along the way

**Comment by faragly** [comment]
> You can create a draft PR to work in the open, show progress, and have conversations about it along the way

@chadoh I am facing problem passing tests with rust contract. https://github.com/near/create-near-app/pull/460

**Comment by faragly** [comment]
@chadoh sorry for delay, I did some updates, you can review my PR.

**Comment by chadoh** [comment]
Great work, @faragly!

**Comment by chadoh** [comment]
@faragly please send an email to me at chad [at] near [dot] org and I will arrange your bounty
