### ISSUE TITLE
Adapt Balancer Frontend for NEAR | Up to $4,000 in $NEAR + $BAL

### ISSUE THREAD

**Issue by ilblackdragon** [near/bounties#26]
# Description
Balancer contracts can be run on NEAR inside the EVM environment. This bounty is to fund porting Balancer’s frontend to work with these contracts.

## Context

- Balancer existing frontend: https://github.com/balancer-labs/balancer-exchange
- Balancer contracts deployable to NEAR node: https://github.com/ilblackdragon/balancer-core
- NEAR Wallet: http://github.com/near/near-wallet
- NEAR Web3.js Provider: https://github.com/near/near-web3-provider/
- NEAR’s “Infura” urls: https://rpc.nearprotocol.com/, https://rpc.testnet.nearprotocol.com/
- Rainbow bridge details: https://near.org/blog/eth-near-rainbow-bridge/
- Bridge codebase: https://github.com/near/rainbow-bridge-cli
- Deployment of Balancer on TestNet: inside `evm.illia` at `0x55a641c83b27fc2dd2bf757c56206114c5b8a46d ` address.
- Example of using bridge: TODO

# Acceptance Criteria

 - [ ] A fork of https://github.com/balancer-labs/balancer-exchange that is pointed at NEAR network
 - [ ] Has a way to “Login with NEAR” using NEAR Wallet
 - [ ] Shows balancers of ERC-20s inside NEAR’s EVM
 - [ ] Allows to swap tokens, signing transactions with NEAR Wallet.
 - [ ] Should run for local node and on TestNet

Additional milestone:
 - [ ] Ability to deposit funds into Rainbow bridge on Ethereum side by signing tx via Metamask
 - [ ] Finalize the relaying tx and get token on NEAR EVM side to use in Balancer

# Bounty

$3,000 in $NEAR + $BAL
Additional milestone: $1,000 in $NEAR + $BAL

**Comment by kamescg** [comment]
In addition to helping with https://github.com/near/bounties/issues/27 happy to help set this up. 

The application should basically do everything the Ethereum version is capable of, correct?

**Comment by ilblackdragon** [comment]
@kamescg yes, correct. Customized to connect with NEAR Wallet instead of Ethereum wallets.

**Comment by vgrichina** [comment]
@kamescg I feel like it might be best to do this before doing https://github.com/near/bounties/issues/27, as it would be easier to launch than integration into wallet (as it will require more scrutiny to be included in wallet itself).

**Comment by kamescg** [comment]
@vgrichina Makes sense. At the moment though, it seems like the Balancer contracts aren't working? I attempted to deploy the contracts myself and also use the factory on chain already, but wasn't able to create a new `BPool` in either case? Maybe that's not the case right now and I'm just missing something.

**Comment by vgrichina** [comment]
@kamescg looks like there might be not enough gas. Maybe makes sense to try with Uniswap contract as it should have less gas usage.

@ilblackdragon @mikedotexe maybe you have more context on EVM /  Balancer? There might be some way to run locally with higher gas limits?

**Comment by Patrick1904** [comment]
@corwinharrell @kcole16 should we provide a design for this?

**Comment by heycorwin** [comment]
@Patrick1904 @kcole16 yes it certainly sounds like it would be appropriate at the very least for this to share common components / visual design with our other products, although I'd expect some flak from Balancer/ETH folks if the UX would otherwise remain unaltered.

**Comment by ilblackdragon** [comment]
@kamescg Currently it is fully working only on the customized node with pre-compile: https://github.com/nearprotocol/nearcore/pull/3257

You can checkout this branch and run with:
```
cargo build -p neard --release
./target/release/neard init
./target/release/neard run
```

We are going to spin up a network to test this shortly.

**Comment by behaviary** [comment]
Just want to check if this is fully claimed @ilblackdragon. There is another team interested in working on it.

**Comment by mikedotexe** [comment]
I believe this bounty is up for grabs at this time.

**Comment by memoriesadrift** [comment]
Hi,
it has recently come to my attention that there are two repos for the balancer frontend - [balancer-exchange](https://github.com/balancer-labs/balancer-exchange) and [balancer-frontend](https://github.com/balancer-labs/balancer-frontend).
This bounty specifies a fork of the balancer-exchange repo, is there some reason for this?
The balancer-frontend repo is a more recent version of the frontend and I was wondering whether forking that repo would be okay for the purpose of bounty.
Thanks in advance!

**Comment by memoriesadrift** [comment]
@mikedotexe @corwinharrell @ilblackdragon pinging regarding my above question.

**Comment by gabrielKerekes** [comment]
Hi all, I am a member of @memoriesadrift 's team. We've managed to make a working prototype of balancer frontend working on top of NEAR - using the near-web3-provider. The app is deployed at https://vacuumlabs-balancer.herokuapp.com/. Currently it's possible to swap the two tokens (GKC1, GKC2) using 2 hardcoded pools. It's not perfect, but this is almost as far as we can get without further discussion. It would be great if you could take a look at the demo, let us know if this is what you expected and if we could discuss next steps.

You can test it out with the following test account which has some of those tokens minted:
Account ID: `vacuumlabs-balancer.betanet`
Seed phrase: `report laugh solid west rescue clown front bundle market garbage goose year`
(hopefully it won't get depleted too fast :wink:)

The code can be found at https://github.com/vacuumlabs/balancer-frontend/tree/near.

**Comment by alexauroradev** [comment]
@gabrielKerekes , hi there. Can you please check the seed phrase? I cannot recover the account using it.

**Comment by gabrielKerekes** [comment]
I think there might be a problem with the betanet wallet at the moment. I haven't been able to recover any of my accounts today. Can you maybe try if you can recover any other account?

**Comment by gabrielKerekes** [comment]
As requested via Discord, we have recorded a short demo video of our Balancer working on betanet and localnet. Here's a link to the video on [Google Drive](https://drive.google.com/file/d/1hni54DvT7gRAz7wjZMc-OTQykiDKsZOC/view). In the end we decided not to describe how it works in the video, since that would make the video quite long - it's already longer than expected I think.

We've also written documentation for the whole project in [this Google Doc](https://docs.google.com/document/d/1bPgVOAkBrEmH-vMjCNlIxQoDoG3mZMG1wP-UWWS0jww/edit?usp=sharing).

Please let us know your feedback and we think it would be best if we could schedule a call to discuss potential further steps.

Thanks!

P.S.: Account recovery using seed phrase still seems to be broken on Betanet.

**Comment by mikedotexe** [comment]
Thanks @gabrielKerekes , we're going over a much improved bounties workflow right now. Thank you so much for making this video and your patience, we'll be getting back soon.
