### ISSUE TITLE
Integrate Balancer into NEAR Wallet | Up to $6,000 in $NEAR + $BAL

### ISSUE THREAD

**Issue by ilblackdragon** [near/bounties#27]
# Description

Balancer contracts can be run on NEAR inside the EVM environment. This bounty is to fund adding interfaces to swap tokens using Balancer into NEAR Wallet.

## Context

 - Balancer contracts deployable to NEAR node: https://github.com/ilblackdragon/balancer-core
 - Balancer existing frontend: https://github.com/balancer-labs/balancer-exchange
 - NEAR Wallet: http://github.com/near/near-wallet
 - NEAR Web3.js Provider: https://github.com/near/near-web3-provider/
 - NEAR’s “Infura” urls: https://rpc.nearprotocol.com/, https://rpc.testnet.nearprotocol.com/
 - Deployment of Balancer on TestNet: inside `evm.illia` at `0x55a641c83b27fc2dd2bf757c56206114c5b8a46d` address.

# Acceptance Criteria

 - [ ] NEAR Wallet has a new page for trading tokens, with matching design to the rest of UI
 - [ ] UI allows to select a pair to trade from tokens that are whitelisted or specified by account id. It shows the current balance of these tokens.
 - [ ] Allows to swap one token for another token using Balancer contracts. Doesn’t require additional confirmation as already internal in the wallet.

# Bounty

$4,000 in $NEAR + $BAL
Extra for matching design: $2,000 in $NEAR + $BAL

**Comment by kamescg** [comment]
Would love to handle this bounty. Besides the Acceptance Criteria anything else I should be mindful of?

Can handle the design and technical integration.

 In regards to `matching design to the rest of UI` I noticed the Wallet s using Semantic UI in the NEAR wallet. I presume the objective is keep that design system moving forward?

**Comment by kamescg** [comment]
Spent some time getting familiar with the current wallet application setup.

![image](https://user-images.githubusercontent.com/3408362/91669771-7d9eab80-eacc-11ea-941b-886369766311.png)

In regards to completing transactions, thoughts on using a `hooks` based approach? It might be a bit easier to pass around state and action handlers.

Something similar to https://github.com/NoahZinsmeister/web3-react

**Comment by vgrichina** [comment]
@kamescg 

>  I noticed the Wallet s using Semantic UI in the NEAR wallet. 

we aren't using it efficiently, long-term plan is to get rid of this framework cc @Patrick1904

**Comment by vgrichina** [comment]
> In regards to completing transactions, thoughts on using a hooks based approach? It might be a bit easier to pass around state and action handlers.

we are currently using Redux to manage state. It's usage can be combined with hooks (`useDispatch`, `useSelector`, etc)

**Comment by Patrick1904** [comment]
> @kamescg
> 
> > I noticed the Wallet s using Semantic UI in the NEAR wallet.
> 
> we aren't using it efficiently, long-term plan is to get rid of this framework cc @Patrick1904

Yes please refrain from using semantic-ui html (if possible) and utilize styled-components to build any new, re-usable, UI components.

**Comment by kamescg** [comment]
@vgrichina Thanks for heads up. Will reframe from utilizing Semantic UI.

Recently been leaning heavily only on a `hooks` based approach, but won't have an issue hopping back into Redux.

@Patrick1904 Sounds good. I'll add a few layout modules (Flex/Box components) to setup the Swap components.

Anything else I need to do before being assigned to the issue?

**Comment by kamescg** [comment]
Diving into the Redux setup now. Quick question.

Should contract state (request/success/failure) be kept in a generalized object or should the state specifically track swaps?

In the past I had a Redux setup that managed generalized contract interactions, instead of adding actions/reducers specific to each smart contract.

https://github.com/kamescg/mvp/tree/c626957a90e38a09e7dd94abecf4b464a0d33799/src/core/assimilation/symbiosis/ethers

Could add something similar where contract interactions are managed in their own store key.. 
 
Or should I follow the current pattern now where everything is stored in the `accounts` key and just manage state?

![image](https://user-images.githubusercontent.com/3408362/91933336-809cc600-ec9d-11ea-9a71-bed28e1664bc.png)

**Comment by vgrichina** [comment]
@kamescg I think it's best if your UI uses separate state root to avoid interfering with other stuff in wallet.

> In the past I had a Redux setup that managed generalized contract interactions, instead of adding actions/reducers specific to each smart contract.

That seems to be a bit counter productive. Ideally one Redux action should correspond to one specific action in business logic (vs being generalized). If something needs to happen for multiple different actions – it can be generalized in reducer / middleware.

**Comment by kamescg** [comment]
@vgrichina True. I think it just depends on the application. At the time was setting up a way to dynamically add new contract functionality to the app structure without writing a bunch of Redux boilerplate (which gets old after awhile), but for this situation would probably be overkill.

In terms of managing contract, should I just add classes (similar to the wallet) and have components initialize those individually or should I take a more global approach where a single contract instance in maintained and information like `tokenBalance` is also stored in Redux? 

![image](https://user-images.githubusercontent.com/3408362/92131463-e29f1d80-edba-11ea-82dc-9bc05ce4c62c.png)

**Comment by vgrichina** [comment]
@kamescg given that we don't have any support for custom tokens in wallet (and it yet to be designed), I think it's best to make standalone demo first: https://github.com/near/bounties/issues/26

It seems like building this into wallet would require a lot of design effort in terms of how do we implement custom tokens in wallet itself, whether we cache any state like token balances, etc

**Comment by ghost** [comment]
still available?

**Comment by bi23com** [comment]
still available?

**Comment by frol** [comment]
@kcole16 Can you assess the bounty availability?

**Comment by behaviary** [comment]
Just want to check if this is fully claimed @ilblackdragon @kcole16 . There is another team interested in working on it.

**Comment by le-dawg** [comment]
> Just want to check if this is fully claimed @ilblackdragon @kcole16 . There is another team interested in working on it.

Open or closed team?

**Comment by kcole16** [comment]
Hey everyone! Closing this for now as it is not currently relevant. Balancer will run on the NEAR EVM, and users will use wallets supporting the EVM and custom networks like MetaMask.
