### ISSUE TITLE
Rainbow Bridge NFT Connector | Bountry $TBD in NEAR

### ISSUE THREAD

**Issue by ilblackdragon** [near/bounties#29]
# Description
Implement an NFT connector for Rainbow Bridge.

General idea is to fork Token Connector and adjust it to support NFTs (ERC-721 & NEP-4)

## Context

 - Overall details about Rainbow bridge: https://near.org/blog/eth-near-rainbow-bridge/
 - Entry point for implementation: https://github.com/near/rainbow-bridge-cli
 - ERC-20 token connector: https://github.com/near/rainbow-token-connector
 - Ethereum's standard for NFTs ERC-721: https://eips.ethereum.org/EIPS/eip-721
 - NEAR's standard for NFTs NEP-4: https://github.com/nearprotocol/NEPs/pull/4
 - Example of NEAR's implementation of NEP-4: https://github.com/near-examples/NFT
 - NEAR-based Corgi's NFT: http://corgis.near.org/  + source code: https://github.com/nearprotocol/corgis

# Acceptance Criteria

* [ ] Fork of https://github.com/near/rainbow-token-connector contracts that implements it for NFTs: `BridgeNFTFactory`, `BridgeNFT` token on both NEAR and Ethereum sides.
* [ ] Integration test for NEAR, that deploys test NFT contract, BridgeNFTFactory and tests that with a "mocked" prover deposit/withdraw of NEAR's NFT happen and that with a prove, it can deploy and mint new NFTs bridged from Ethereum side.
* [ ] Integration test for Ethereum, that deploys test NFT contract, BridgeNFTFactory and tests that with a "mocked" prover deposit/withdraw of Ethereum's NFT happen and that with a prove, it can deploy and mint new NFTs bridged from NEAR side.

Extra:
* [ ] Example with UI to bridge Corgi's (or any other NFT) from NEAR to Ethereum and back.

# Bounty
$TBD in NEAR

**Comment by vince0656** [comment]
Sent @potatodepaulo a message on discord about working on this as part of the hackathon

**Comment by vince0656** [comment]
@ilblackdragon @potatodepaulo see draft PR above. Made progress during the hackathon but started working on things pre token connector (the token connector wasn't being used in the CLI when I had cloned the repo and the contracts repos too)

**Comment by vince0656** [comment]
https://medium.com/@vince0656/bridging-ethereum-nfts-to-near-505a272ec949

**Comment by alexauroradev** [comment]
Moved to https://github.com/near/rainbow-non-fungible-token-connector/issues/1

**Comment by cameron-NEAR** [comment]
Has this bounty been finalized and paid? @ilblackdragon @vince0656 
It seems so, I just want to double check before closing it.

**Comment by cameron-NEAR** [comment]
Hey, has this bounty been completed? I'm happy to help find a team to complete it if not. @ilblackdragon

**Comment by starpause** [comment]
Based on chat we should focus on ERC-1155 & [NEP-171](https://github.com/near/NEPs/blob/master/specs/Standards/NonFungibleToken/Core.md). Still open and we have the [#CreatorsAndCommunities Hackathon](https://createbase.community/hackathon/) kicking off May 15 (Fri)!

**Comment by ht55ght55** [comment]
What is going on with this bounty?  It seems like there hasn't been any updates on any of the bounties in this repo for a while....

**Comment by ilblackdragon** [comment]
There has been a bunch more work outside of the bounty process. I'll close this bounty.
