### ISSUE TITLE
Implement Geomap of nodes in NEAR Explorer | Bounty: $500 USD in NEAR

### ISSUE THREAD

**Issue by ilblackdragon** [near/bounties#3]
### Describe your idea or initiative here
Implement https://github.com/near/near-explorer/issues/299

### Bounty

USD $500 in NEAR tokens

**Comment by oancius** [comment]
Started working on this!

Fetched and displayed data in a basic way, working on design and animations.

**Comment by oancius** [comment]
Hi @ilblackdragon, 

Just opened this PR (https://github.com/near/near-explorer/pull/335) that implements https://github.com/near/near-explorer/issues/299 and I'm looking for feedback. 

cc @miladmostavi

**Comment by ilblackdragon** [comment]
It has been implemented and live for awhile now. Closing this bounty.
