### ISSUE TITLE
Rainbow Bridge Ampleforth Connector | Bounty TBD

### ISSUE THREAD

**Issue by ilblackdragon** [near/bounties#30]
# NEAR Bounty Terms

This is part of https://near.org/rainbow hackathon.

# Description
Implement Rainbow bridge connector for Ampleforth.

## Context
AMPL is an adaptive base-money, that adjusts total supply based on supply and demand. Can learn more https://www.ampleforth.org/

Rainbow Bridge has a generic ERC-20 connector implementation. But AMPL token won't work correctly with it, because of `rebase` - function that changes denomination of the token every day.

This bounty is about cloning a single token connector and customizing it to keep track of rebases and also communicating rebases from Ethereum to NEAR.

## Relevant repos or issues

* Generic erc-20 tokens bridge connector: https://github.com/aurora-is-near/rainbow-token-connector
* ETH connector: https://github.com/aurora-is-near/eth-connector
* NEAR connector: https://github.com/aurora-is-near/near-erc20-connector
* Ampleforth contracts: https://github.com/ampleforth/uFragments

The way to correctly do accounting due to rebases:
 
When amount is deposited / withdrawn from ETH/NEAR is to use internal amount (e.g. divide by total supply). E.g. if Alice has 1,000 AMPL currently and total supply is 2,000, internally she has `100,000,000` (e.g. whatever the internal denomination is used). Which will be sent to the other chain and rehydrated back depending on current rebase.
This is important, because if the event was created pre-rebase, but the token arrives on the other side after rebase happened - the external amount will be incorrect. Internal amount (e.g. pre rescaling with rebase) will allow that on arrival can recalculate based on the current multiplier.

For example Alice sent 50 AMPL to NEAR. Right after the rebase happened and adjusted 2x the total supply. E.g. this 50 AMPL became 100 AMPL. For example the contract on NEAR actually received rebase event before Alice called `deposit` on NEAR side. If `100,000,000` of internal denomination arrive, contract just multiplies back to 1/50,000 and receive 2000 AMPL on NEAR side. 

# Acceptance Criteria
* [ ] Contract on Solidity/Ethereum side that can lock and unlock AMPL. When AMPL gets unlock, the amount should be correct given possible rebases that have happened
* [ ] Contract on Rust/NEAR side that can mint/burn nAMPL. Additionally, it would receive rebase events from AMPL ERC-20 contract and adjust total supply as well.
* [ ] Set of tests that show various usages and conditions of arrival AMPL/rebase between networks
  * [ ] Double withdraw / deposit of AMPL to NEAR
  * [ ] Double rebase test
  * [ ] Avoid rebase test
  * [ ] Rebase and transfer cross chain race condition
  * [ ] Cross-contract call handling AMPL on NEAR during rebase (e.g. withdraw funds before rebase, but arrive back after rebase).

# Bounty
TBD

**Comment by defiboy** [comment]
hello, I would like to start working on this, what do I need to do?

**Comment by ilblackdragon** [comment]
@defiboy assigned it to you here. Feel free to ping us with questions in https://near.chat, also can connect with AMPL team if there are questions.

**Comment by defiboy** [comment]
yes, thanks

**Comment by ilblackdragon** [comment]
@defiboy wanted to check in on the status here

**Comment by cameron-NEAR** [comment]
Hi @defiboy, how is the completion of this bounty going? I'm happy to find someone to complete it if you are no longer interested.

**Comment by cenwadike** [comment]
Hello, I'm interested in this bounty and would like to start working on it.
What do I need to get started?

**Comment by cameron-NEAR** [comment]
I just assigned it to you so feel free to start working on it now! :) 

When do you think you will be able to complete it by?

**Comment by cenwadike** [comment]
Keeping my fingers crossed, hopefully within 3 months.

**Comment by cenwadike** [comment]
@cameron-NEAR  I've constantly received a 404 error when I attempted to view the repo for "Ethereum side: https://github.com/near/rainbow-bridge-sol/tree/master/token-locker ".

Can I have the current and available link to this repo.

**Comment by ilblackdragon** [comment]
@cenwadike sorry for inconvenience. The code of the connectors from both Ethereum and NEAR side was moved to https://github.com/aurora-is-near/rainbow-token-connector.
Updated description as well.

**Comment by cenwadike** [comment]
@ilblackdragon thank you for your response.

**Comment by cenwadike** [comment]
Hello @ilblackdragon, I haven't been paying attention to the project as I've been helping a friend out with his project for an MSc thesis.

I'll be paying more attention here and could be asking some questions soon.

Thanks for being approachable.

**Comment by ilblackdragon** [comment]
I'm going to close this as there is not much progress here in past 1.5y.

**Comment by cenwadike** [comment]
Been on it...the code base is quite large, been trying to understand different parts.
Can I continue to work on it? Have dedicated some effort into it and would like to see it through.

**Comment by ilblackdragon** [comment]
@cenwadike for sure, continue working. just ping here when you have something to share with the bridge team.

**Comment by cenwadike** [comment]
Noted
