### ISSUE TITLE
An idea bank 

### ISSUE THREAD

**Issue by JonaFly** [near/bounties#35]
# Description
An app can post idea on the blockchain

## Context
Everyone can contribute their idea to the system

# Acceptance Criteria
* [ ] [Checkboxes for features that are necessary to this being completed]

# Bounty
$500

**Comment by ilblackdragon** [comment]
Duplicate for https://github.com/near/bounties/issues/12 ?

**Comment by behaviary** [comment]
Closing since this is duped.
