### ISSUE TITLE
Crypto Corgis Cleanup and Extension

### ISSUE THREAD

**Issue by behaviary** [near/bounties#37]
# Description
[Crypto Corgis ](https://corgis.near.org/) is an NFT project that needs a cleanup

## Context
[Crypto Corgis ](https://corgis.near.org/) is an example application that demonstrates some of the features of the NEAR blockchain. Since it's creation, it has not been maintained and deployed on MainNet. This bounty provides funds to update, expand and deploy Crypto Corgis on the NEAR MainNet.

## High Level Requirements
- update all libraries and SDKs to latest versions, fix all breaking changes
- include a market function where users can buy / sell corgis after they have purchased them from the "store" (primary sale from the account that is allowed to mint corgis)
- deploy a version to mainnet that can direct new NEAR users to
- price corgis in yocto NEAR (super small amounts) OR include functionality to sell corgis back to store so users don't have to part with mainnet NEAR tokens

# Acceptance Criteria
Cleanup
* [ ] Implement the NEP4 standard on top of the existing provided front end code (preferable to use Rust)
* [ ] Update the front end to use the newly implemented contract
* [ ] Cleanup animations and CSS in the front end
Features M1 - Basic Corgis
* [ ] Pay to create (mint) Corgis of semi-random size to reflect rarity
* [ ] Send Corgis to any account on NEAR
* [ ] Receive Corgis and view the list of Corgis
* [ ] Share individual Corgis on social media
Features M2 - CorgiMart
* [ ] List Corgis to sell to bidders
* [ ] Bid on Corgis to purchase from sellers
* [ ] Provide an escrow to users to safely transact
Features M3 - Deployable Example & Mainnet Launch
* [ ] Make sure other developers can configure and deploy this app
* [ ] Launch mainnet version of contracts and host frontend on GH pages
* [ ] Sell back to store feature so users don't lose funds

# Bounty
$5000 worth of NEAR

**Comment by ouromoros** [comment]
I would like to work on this bounty if it's still open 😊

**Comment by cameron-NEAR** [comment]
Hi @potatodepaulo, is this bounty still open? If so, @ouromoros seems interested in completing it :)

**Comment by zahhar** [comment]
@potatodepaulo - this bounty was taken some time ago, and now PR is waiting to be merged: https://github.com/nearprotocol/corgis/pull/16
