### ISSUE TITLE
Benchmarking NEAR's network | Bounty: 2000 NEAR

### ISSUE THREAD

**Issue by ilblackdragon** [near/bounties#4]
### Describe your idea or initiative here

Leverage existing scripts to run 100 node network across the globe and build robust benchmarking tools with various loads (create lots of accounts, transfers, smart contracts, etc).

### Bounty

2000 $NEAR

**Comment by fanhuaqiang** [comment]
这样的开源项目很期待你们的成功

**Comment by ilblackdragon** [comment]
Have been implemented internally on the "mixnet".
