### ISSUE TITLE
ETHDenver Bounteez!

### ISSUE THREAD

**Issue by jlwaugh** [near/bounties#40]
# Hack with NEAR ✨

#### Blue Sky Hack :blue_heart:
For teams who build something cool on the NEAR platform or use the Ethneareum Rainbow Bridge.
**2 prizes available, $1000 each**

#### NFTs Bounty 🖼️
Deploy your own store on Mintbase via the NEAR Testnet, and get creative with use cases! NFTs can be more than just collectibles ~ think multi-purpose NFTs. For example, these non-fungible tokens may give you voting power on a certain website, let your video game character run faster, or give you a real physical object.
**$1000 prize**

#### NEAR + Ceramic Bounty 🔶
**$500 each** for best project that uses both technologies!

#### NEAR + Textile Bounty ⛅
**$500 prize** for best project that uses both technologies!

#### Girl Power Bounty 👩
Your team must have at least 2 womxn or be 50% womxn. You don't have to build on NEAR, you can build anything you want on any blockchain platform or technology.
**2 prizes available, $500 each**

#### Global Citizens Bounty 🌎 🌍 🌏
We'd like to see teams of people from different places around the world build something cool together. 
**$500 prize**

#### Social Impact Bounty 💖
This one is for projects who promote social good. Some examples: solutions to help fund ongoing research or open-source development, the creation of on-ramps for those that may not have easy access to crypto, or a DAO that can bring a community together to solve social problems.
**$500 prize**

**Comment by cameron-NEAR** [comment]
Hey @jlwaugh, can I close this?
