### ISSUE TITLE
New frontend for BerryClub | $4000 in $NEAR x 3

### ISSUE THREAD

**Issue by ilblackdragon** [near/bounties#45]
# Description

Design and implement an appealing frontend for BerryClub ecosystem.
The goal is to make it attractive to non crypto, art-minded people who might be interested to explore.

## Context

BerryClub is a a novel way to co-create art on a limited space using token economics to balance incentives:
 - https://berryclub.io
 - https://farm.berryclub.io/
 - https://berry.cards/

# Acceptance Criteria
Functionality of BerryClub, Berry Farm and Berry Cards in one UI

* [ ] Login with NEAR
* [ ] BerryClub
    * [ ] Buy avocado's
    * [ ] Show the board and allow to draw
    * [ ] See standings tables for berry club
    * [ ] Gallery of historical videos
* [ ] Berry Farm
   * [ ] Display all the data
* [ ] Berry Cards
    * [ ] Naturally into gallery of historical videos, can build the UI of voting for cards
    * [ ] See top cards
    * [ ] Buy cards
* [ ] Stats
   * [ ] Total stats across all these contracts: total number of accounts played, total number of cards, avocado sold, banana mines, cucumber staked, etc.

For extra bonus $NEAR: integrate https://near.fm capability to chat by filtering to #berryclub tag.

# Bounty
$4000 in NEAR for 3 *complete* submissions will get receive the bounty pay out.

Please comment here if you are working on this bounty and leave your timeline. If you have something in progress - share it as well for community to try / comment.

**Comment by mrrobot16** [comment]
Hello world! Do we have any info about how the new frontend is expected to look like o maybe look a like? @ilblackdragon

**Comment by peterfeng1984** [comment]
My team can do it. I wonder if you are satisfied with this design? Looking forward to  reply @ilblackdragon, I will finish it as soon as possible
![image](https://user-images.githubusercontent.com/79548864/112934638-c860ce80-9154-11eb-9d76-d4a1ec855c7e.png)
![image](https://user-images.githubusercontent.com/79548864/112934656-ceef4600-9154-11eb-8a6c-fcd05f2eec28.png)
![image](https://user-images.githubusercontent.com/79548864/112934671-d6165400-9154-11eb-9317-4c54d8e83292.png)
![image](https://user-images.githubusercontent.com/79548864/112934685-db739e80-9154-11eb-8a4c-5811bd5b69c1.png)

**Comment by JonaFly** [comment]
Dear Illia,

We have checked the links and info. since we are Front-end developer and very interested in BerryClub.
We wanna finish it and contribute on it.

**Comment by ilblackdragon** [comment]
Hi folks,

Sorry for changing rules.

I think let's split this bounty into stages to design first and implement second:
 - Post who will work on mocks first (e.g designers) and how long it will take. Post your previous portfolio.
 - I'll approve you for design.
 - Post here mocks after you completed design. If you are approved - you will get paid a portion of the reward either way. If there is already 3 approved to work on designs - you can gamble and post your mocks as well.
 - Based on the published mocks we can decide which one should be implemented via simple community vote.
 - Frontend developers can start working on that design.

**Comment by LegalOPC** [comment]
how about Buidl a V2 of Berry club based on V1 ?
1,UI
2,token economy

just like uniswap v1 to uniswap V2

**Comment by 15060322123** [comment]
I use the design

**Comment by 15060322123** [comment]
I use the design
1 UI

**Comment by 0xhn** [comment]
I am using this website and I know what it needs.  I use the design
1. UI
2. two weeks

![30501025ef425a50261c3d18c7648909](https://user-images.githubusercontent.com/31805829/113108910-113d8380-9238-11eb-9fce-8730c36eea98.png)
![arm09-adgoi](https://user-images.githubusercontent.com/31805829/113108926-14d10a80-9238-11eb-8d73-60fe692a4441.jpg)

**Comment by ilblackdragon** [comment]
Approve for mock up @15060322123: Looks like an interesting concept. Please start by doing mock ups for Berry Club.

Approve for mock up @peterfeng1984: I'm not sure, the designs you shown are not super exciting for social gaming type of application. But feel free to post some mock ups of Berry Club itself in your concept.

**Comment by ilblackdragon** [comment]
@wjy7551376, @mrrobot16 can you post the concepts you are thinking / your portfolio and timeline for mockups first?

**Comment by ilblackdragon** [comment]
@ethyuan I think for v2 of the BerryClub itself this can be separate discussion from frontend. 

Do you have something specific in mind?

**Comment by 0xhn** [comment]
@ilblackdragon Thanks，This is the template style that we designed
![UGS9G}(8@_U4}OXLO6 V35X](https://user-images.githubusercontent.com/31805829/113688547-fb2e3800-96fb-11eb-952a-30e9eefed895.jpg)

**Comment by ilblackdragon** [comment]
@15060322123 may be can you start with Berryclub itself?
For berry cards - what is the numbers on the right of the picture?

**Comment by ilblackdragon** [comment]
@wjy7551376, @mrrobot16 do you guys want to post some mocks you have in mind?

**Comment by 0xhn** [comment]
@ilblackdragon Yeah , you can check this
![微信图片_202104151012003](https://user-images.githubusercontent.com/31805829/114804209-85992a80-9dd3-11eb-8848-a1d4d74749a3.jpg)
![微信图片_20210415101200](https://user-images.githubusercontent.com/31805829/114804213-8762ee00-9dd3-11eb-8352-87d652ea727a.jpg)
![微信图片_202104151012001](https://user-images.githubusercontent.com/31805829/114804215-87fb8480-9dd3-11eb-97f7-0ac56d657baa.jpg)
![微信图片_202104151012002](https://user-images.githubusercontent.com/31805829/114804217-88941b00-9dd3-11eb-8abd-91895d64ab46.jpg)

**Comment by 0xhn** [comment]
@ilblackdragon  The background color scheme can be adjusted
![dfbfecba923d094ed408c7eb4cc0e88](https://user-images.githubusercontent.com/31805829/114992641-8f9f5400-9ecd-11eb-8533-9516d738ddd6.jpg)

**Comment by jilt** [comment]
Hi I would like to setup a bounty on this on the createbase hackathon, for building a VR interface using berryclub dynamics, would you be interested to contribute to the bounty?

**Comment by jilt** [comment]
I sent a DM to illia on the near forum with the details

**Comment by andrewmamus** [comment]
Is this bounty still available? I am a reactjs and nextjs developer any UI choosing I want to work on the frontend

**Comment by cameron-NEAR** [comment]
Hey @andrewmamus! This bounty is available but it still requires design mockups. Would you be interested in submitting designs or only completing the front-end development component?

**Comment by cameron-NEAR** [comment]
@andrewmamus - if you're not a designer, feel free to DM me on Telegram @camerondennis because I have other cool projects for you :)

**Comment by aj-maz** [comment]
Hi I just made this rough demo of my idea for redesigning of berry club. I'm wondering whether it's satisfying or not? I will code it myself. I'm more coder than designer. design will get alot better I just created as fast as possible to see whether you're intrested in it or not.
![Desktop - 1](https://user-images.githubusercontent.com/64213712/126189406-f3ffd66d-e455-45bf-ab65-9e08c7fa9a79.png)

**Comment by cryptovaibhav** [comment]
Hi, Is this bounty still open ? I am a full stack developer looking to contribute to the NEARverse.

**Comment by JoseGabriel-web** [comment]
I am a Reactjs developer, Is the bounty still available or any others I could help with?

**Comment by vnlongbk** [comment]
<img width="1424" alt="Screen Shot 2021-11-03 at 13 52 28" src="https://user-images.githubusercontent.com/37822634/140019635-3d42d872-548e-4a68-8fc0-4ea50a680fd4.png">

Hi, I have a demo for berry cards, i hope you will check it out, thank you!
Link: https://vnlongbk.github.io/nedo/
@ilblackdragon

**Comment by lin-nguyen** [comment]
hi @vnlongbk , can I join with you :D

**Comment by mindsgn** [comment]
> # Description
> Design and implement an appealing frontend for BerryClub ecosystem. The goal is to make it attractive to non crypto, art-minded people who might be interested to explore.
> 
> ## Context
> BerryClub is a a novel way to co-create art on a limited space using token economics to balance incentives:
> 
> * https://berryclub.io
> * https://farm.berryclub.io/
> * https://berry.cards/
> 
> # Acceptance Criteria
> Functionality of BerryClub, Berry Farm and Berry Cards in one UI
> 
> * [ ]  Login with NEAR
> * [ ]  BerryClub
>   
>   * [ ]  Buy avocado's
>   * [ ]  Show the board and allow to draw
>   * [ ]  See standings tables for berry club
>   * [ ]  Gallery of historical videos
> * [ ]  Berry Farm
>   
>   * [ ]  Display all the data
> * [ ]  Berry Cards
>   
>   * [ ]  Naturally into gallery of historical videos, can build the UI of voting for cards
>   * [ ]  See top cards
>   * [ ]  Buy cards
> * [ ]  Stats
>   
>   * [ ]  Total stats across all these contracts: total number of accounts played, total number of cards, avocado sold, banana mines, cucumber staked, etc.
> 
> For extra bonus $NEAR: integrate https://near.fm capability to chat by filtering to #berryclub tag.
> 
> # Bounty
> $4000 in NEAR for 3 _complete_ submissions will get receive the bounty pay out.
> 
> Please comment here if you are working on this bounty and leave your timeline. If you have something in progress - share it as well for community to try / comment.

Hi @ilblackdragon I just would like to know if this has been fulfilled?.

**Comment by ilblackdragon** [comment]
@vnlongbk looks pretty good.

@15060322123 good start but would need some iterations - typefonts are really off and would be good to have better menus.

This has not been fulfilled.
Sadly, I'm not a good person to manage this process going forward and Berry Club developer is not really active here either.

Let's do next thing: if someone wants to do this - you need to launch this frontends live on mainnet and post here links for working product. Code needs to be open source. 3 first posts that match the criteria above will get paid.

**Comment by mdb1710** [comment]
@ilblackdragon I would love to give this a shot if it hasn't been fulfilled yet.  I'm a developer in the states who just completed the NEAR Certified Developer (NCD) L1 Certification.  I can make it open-source with the requirement above at about 3-4 weeks time if not sooner.

**Comment by rohannrk** [comment]
Hey @Ajand can we collaborate. I can work on design work.....as I am just starting out with frontend dev??

**Comment by Oltisdotcom** [comment]
@ilblackdragon Here is our vision, we creating marketplaces for 20m items,

Sample for Berry Cards:
https://drive.google.com/drive/folders/1eiJ7BUwuq8tjKljHs67AkCcsmURaq4ke

Thanks, waiting for comments

**Comment by mindsgn** [comment]
hey @ilblackdragon are you from berry club?.

**Comment by tuananhh10** [comment]
> 

I'm gonna do it

**Comment by aashiriftikhar** [comment]
Hey @ilblackdragon , Just came across this bounty and Berry Club looks like an exciting project to work on. My team and I will be working on the design starting Monday and will be sharing the designs here in a week. Should I get the design approved first before working on the development and deployment? Or are we to move right ahead with the development to become eligible for the bounty? 

Also, is there any way we can communicate more smoothly?

**Comment by gvincenta** [comment]
Happy to work along with others and get the bounty, I am a typescript react developer with 2 years of experience @ilblackdragon

**Comment by ilblackdragon** [comment]
Because it seems like people don't see my message, I'll close this issue at this point.

Feel free to create alternative frontends and share them with community to receive retroactive rewards.

**Comment by andrewmamus** [comment]
Ok sir
