### ISSUE TITLE
Permissioned API for New User Onboarding

### ISSUE THREAD

**Issue by cameron-NEAR** [near/bounties#49]
# Description
Permissioned API for automating users sending assets to not-yet-existent NEAR accounts.

## Context
Deterministically associate a Discord user with a public key so one can send and receive NEAR without needing a NEAR account until they create a NEAR Name.

# Acceptance Criteria
* [ ] Allow users to send assets to not-yet-existent NEAR accounts
* [ ]  Deterministically associate a discord user with a public key
* [ ] Initialize accounts with minimum balance to create a NEAR Account ID and ensure that it can only happen once via OAuth login

# Bounty 
[$6,000 USD in NEAR]

**Comment by Sladuca** [comment]
Hey Cameron! My friend @Lev-Stambler and I would like to take on this bounty.

**Comment by cameron-NEAR** [comment]
Great! I just assigned it to you and will follow up in two weeks for an update.

**Comment by Lev-Stambler** [comment]
I would love to take this up!

**Comment by Lev-Stambler** [comment]
We are ready to have our work reviewed! Find the [test site](https://baf-wallet-v2.vercel.app/) and [code base](https://github.com/bafnetwork/baf-wallet-v2)

**Comment by Lev-Stambler** [comment]
Hi, just also bumping this issue as we have not heard a response on the bounty.

**Comment by zavodil** [comment]
Could you provide a tutorial how to:
```
- Allow users to send assets to not-yet-existent NEAR accounts
- Deterministically associate a discord user with a public key
```

Provided UI doesn't allow to perform this in intuitive way.

---

Could you provide a link to the codebase where you perform the bounty's objective: `Permissioned API + Contract to Automates New User Onboarding `. How to find API endpoints? You provided the link to the whole wallet, it's difficult to reuse it and for instance redeploy it in the NEAR mainnet or betanet.

**Comment by cameron-NEAR** [comment]
I'm separating the "Permissioned API" and "Contract to Automates New User Onboarding" components of this bounty because it was not clear enough. The new title, price, and acceptance criteria is updated above. @Sladuca @Lev-Stambler
