### ISSUE TITLE
Implement Top Level Account Registrar Contract | Bounty: $14,000 in $NEAR

### ISSUE THREAD

**Issue by ilblackdragon** [near/bounties#5]
### Describe your idea or initiative here

Implement Top Level Account Registrar Contract.
Details are here https://github.com/near/initial-contracts/issues/25

### Bounty

$14,000 in $NEAR

**Comment by aistoc** [comment]
DigitalMob team is working on this. Currently getting more insight on this issue while training our Rust skills.

**Comment by mikedotexe** [comment]
@aistoc is this in development?

**Comment by aistoc** [comment]
@mikedotexe, this was completed some while ago.

**Comment by mikedotexe** [comment]
Adding to thread that the repo in discussion is:
https://github.com/CrossChainLabs/near-registrar

**Comment by cameron-NEAR** [comment]
Is this bounty completed? If so, can I close it?@mikedotexe @ilblackdragon

**Comment by ilblackdragon** [comment]
Yes, it's completed.
