### ISSUE TITLE
Multi-Chain UI Web Wallet 

### ISSUE THREAD

**Issue by cameron-NEAR** [near/bounties#50]
# Description
Easy to use, multi-chain web wallet that a user can sign into using OAuth providers and be extendable with application-specific UI’s for assets.

## Context
As more DAOs are created and more organizations incorporate crypto into their community that contains non-crypto-native individuals, the “list of assets” UI that we typically see in most wallets will not be good enough UX. For instance, an education or projects DAO will be minting assets for things that might include “Proof of Attendance” tokens, learning badges, project ownership tokens - all of which would make more sense if they were presented as they are intended to be used. For example, learning badges and project ownership tokens can be represented in a resume-like format, which makes the wallet far more useful to the user than if it was just a list of asset names and contract addresses. The wallet would also be integrated with tor.us such that an account’s private and public keys are derived from oauth providers. Thus, users can sign in with oauth providers and not have to worry about storing private keys/ mnemonics.

# Acceptance Criteria
* [ ] Basic UI flow that allows users to send and receive assets, view how much of each asset they have
* [ ] Approval page that takes parameters through the URL and allows users to approve / disapprove translation
* [ ] Choose an account ID
* [ ] Ability to log in with Discord
* [ ] Downloading key pairs as a JSON file

# Bounty 
[$8,000 USD in NEAR]

**Comment by Sladuca** [comment]
Hey Cameron! My friend @Lev-Stambler and I would like to take on this bounty.

**Comment by cameron-NEAR** [comment]
Great! I just assigned it to you and will follow up in two weeks for an update.

**Comment by Lev-Stambler** [comment]
I would love to take it up!

**Comment by Lev-Stambler** [comment]
We are ready to have our work reviewed! Find the [test site](https://baf-wallet-v2.vercel.app/) and [code base](https://github.com/bafnetwork/baf-wallet-v2)

**Comment by Lev-Stambler** [comment]
Hi, just bumping this issue as we have not heard a response on the bounty.

**Comment by zavodil** [comment]
Please provide more information and describe how did you achieve Acceptance Criteria. Test site and code base are not intuitive as I mentioned in #49

**Comment by ilblackdragon** [comment]
I'm going to close stuff that doesn't have a clear owner.
