### ISSUE TITLE
MultiSafe V1 - $15,000 in NEAR

### ISSUE THREAD

**Issue by cameron-NEAR** [near/bounties#52]
# Description
Continue the development and launch Multisafe, a multi-signature web application, to NEAR mainnet.

## Context
Multisafe is a multi-signature NEAR webapp that enables multiple parties to confirm a transaction before it can be executed. It is currently on testnet and we are looking for someone to connect Ledger to Multisafe so users can create, approve, and decline transaction requests. Furthermore, this bounty requires the addition of features to the Multisafe list and dashboard. Lastly it is expected the webapp will be quality tested and the frontend will be fully documented.

Upon successful submission of this bounty, we are beyond the scope of this bounty also interested in incentivising this UI to become your baby - so that the NEAR ecosystem can rest assured the code will be maintained when needed. 

Please refer to the following links of the current website, UX mockups, GitHub, and Netlify. 

Current Website: https://multisafe.io/
UX Mockups: https://4irelabs.invisionapp.com/console/share/HP24UUSM2X/505544846
Netlify: https://multisafe-dev.netlify.app/get-started 
GitHub: https://github.com/multi-safe/ui.multisafe 

# Acceptance Criteria

**General** 
* [x] A recorded video that walks through the following new features. 

**Ledger**
* [x] User can login to Multisafe app without redirections to NEAR wallet.
* [x] User create / approve / decline requests without redirections to NEAR wallet.

**Dashboard**
* [x] In the list of requests - users can see time when request was created.
* [x] Users can see pending requests in the separate tab.
* [x] Users can see requests history in the separate tab.
* [x] When request is finished (signs enough / request was rejected) - it disappears from **pending** tab and appears in **history** tab.

**Multisafe list**
* [ ] Users can remove Multisafes from their list of connected Multisafes (both read only and their Multisafes).
* [x] Users can rename Multisafes from their list of connected Multisafes (both read only and their Multisafes).

# Bounty
$15,000 in NEAR

**Comment by nikbhintade** [comment]
Hi @cameron-NEAR, is this a UI bounty or smart contract? Because you have labeled it as `rust` but in criteria, there isn't any rust requirement.

**Comment by nikbhintade** [comment]
@cameron-NEAR do you have deadline for this bounty?
Becuase I think I can do it but buying new ledger device takes 3 weeks to arrive that's why I am asking

**Comment by cameron-NEAR** [comment]
Hi @nikbhintade! This is a UI bounty and we would like it completed ASAP. I'm happy to assign it to you if you can get started on it before the ledger arrives. Otherwise, we can wait until it does

**Comment by nikbhintade** [comment]
@cameron-NEAR If you can assign me to this task that will be nice I can start working on other tasks like dashboard and mulitsafe list till my ledger device comes.

**Comment by cameron-NEAR** [comment]
Great! I just assigned you and will follow up in a couple weeks to discuss your progress :)

**Comment by eclipseeer** [comment]
@cameron-NEAR Hi, is this task in progress, or can I take it?

**Comment by cameron-NEAR** [comment]
Hey @eclipseeer! This is not assigned yet. Do you have an idea of when you will be able to complete it by?

**Comment by eclipseeer** [comment]
@cameron-NEAR Do you like to discuss details in the Telegram?

**Comment by eclipseeer** [comment]
Progress update: I've done testing connection and signing tx by ledger on the test app via USB. Now I integrate ledger connection UI into the Multisafe app - the user will be able to choose between near wallet and ledger, and choose which account he wants to use in case if he has multiple accounts created by a single ledger.
