### ISSUE TITLE
Found bug in near

### ISSUE THREAD

**Issue by shubh80032** [near/bounties#60]
# Description
[A single sentence describing the project]
Yes I do some random research and then suddenly it's happen 
Your near wallet give user a small locked balance of 0.02 near which can be locked or not transferable to exchange But I have transferred those balance to exchange

## Context
[Some background and explanation on why this is important]
This is important because if team not fixed the issue and the bug got viral everybody make unlimited multiple accounts and collect that near so this is not good for near protocol 

# Acceptance Criteria
* [ ✓] [Checkboxes for features that are necessary to this being completed]

# Bounty
[Amount paid in NEAR]
500 near

**Comment by stefanopepe** [comment]
The issue was already reported by another user on July 6th, a bounty was paid and a fix is underway.
Thank you for taking the time to report this problem, and feel free to share any other bug you find!

**Comment by shubh80032** [comment]
Ohk
