### ISSUE TITLE
NEAR Explorer i18n support and Simplified Chinese translation

### ISSUE THREAD

**Issue by think-in-universe** [near/bounties#61]
# Description
To make NEAR Explorer usable for people speaking different langauges, we'd like to add i18n support for Explorer. In this bounty, you need to refactor NEAR Explorer code to support i18n, and also translate all English i18n strings into Simplified Chinese. 

## Context
As the NEAR ecosystem grows, we would like to have a localized user interface for developers and users in different languages to view and use the explorer. This will improve the user experience and increase adoption.

# Acceptance Criteria
* [x] All the following pages, are refactored with packages like [`react-localize-redux`](https://ryandrewjohnson.github.io/react-localize-redux-docs/).
  - [x] Home: https://explorer.near.org/
  - [x] Accounts and Account Details: https://explorer.near.org/accounts and https://explorer.near.org/accounts/alice.near
  - [x] Block and Block Details: https://explorer.near.org/blocks and https://explorer.near.org/blocks/A7Zo9nAYNbfQgRbhAYg6uRYHDESH2oZk2carYczfAc2L
  - [x] Transactions and Transaction Details: https://explorer.near.org/transactions and https://explorer.near.org/transactions/7rFLj7Fp8PHW9rhr9Ye2LMHcseuGeMNtbiuq5mbbR1y6
  - [x] Nodes: https://explorer.near.org/nodes/validators
  - [x] Stats & Charts: https://explorer.near.org/stats
* [x] All the English i18n strings have a corresponding Simplified Chinese version ready in the format of i18n JSON strings
* [x] Explorer functions well for both English and Simplified Chinese version, which means the refactoring won't break the English version

# Bounty
$500 USD paid in $NEAR

**Comment by think-in-universe** [comment]
@IsQiao is interested to work on the bounty and actually have done most of the work already in the PRs: https://github.com/near/near-explorer/pull/684 and https://github.com/near/near-explorer/pull/691

**Comment by frol** [comment]
@think-in-universe Is it completed now? @IsQiao Thanks for your contribution!

**Comment by think-in-universe** [comment]
@frol yes, Frol. We already paid the bounty. 

I'm asking @cameron-NEAR to help confirm and close the bounty if it's OK.

**Comment by IsQiao** [comment]
Hi, I have finished the feature. it is merged into master branch. thanks.

**Comment by think-in-universe** [comment]
@IsQiao thanks Qiao. great work! looking forward to more contribution from you 🚀
