### ISSUE TITLE
NEAR Explorer translation for Vietnamese Users

### ISSUE THREAD

**Issue by think-in-universe** [near/bounties#62]
# Description
To make NEAR Explorer usable for people speaking different languages, we'd like to add i18n support for Explorer. 
In this bounty, you need to translate all English i18n strings into Vietnamese, and add localization support such as date/time format, etc.

## Context
In the bounty, https://github.com/near/bounties/issues/61, we already refactored Explorer to support i18n, and added Simplified Chinese translation. In this bounty, we'd like you to help to enhance Explorer to support Vietnamese. 

- Explorer Frontend code repository: https://github.com/near/near-explorer/tree/master/frontend

## Skill Requirement
- JavaScript or TypeScript, React
- How i18n works in React

# Acceptance Criteria
* [ ] All the following pages, are translated into Vietnamese:
  - [ ] Home: https://explorer.near.org/
  - [ ] Accounts and Account Details: https://explorer.near.org/accounts and https://explorer.near.org/accounts/alice.near
  - [ ] Block and Block Details: https://explorer.near.org/blocks and https://explorer.near.org/blocks/A7Zo9nAYNbfQgRbhAYg6uRYHDESH2oZk2carYczfAc2L
  - [ ] Transactions and Transaction Details: https://explorer.near.org/transactions and https://explorer.near.org/transactions/7rFLj7Fp8PHW9rhr9Ye2LMHcseuGeMNtbiuq5mbbR1y6
  - [ ] Nodes: https://explorer.near.org/nodes/validators
  - [ ] Stats & Charts: https://explorer.near.org/stats
* [ ] All the [English i18n strings](https://github.com/near/near-explorer/blob/master/frontend/src/translations/en.global.json) have a corresponding Vietnamese version ready in the format of i18n JSON strings
* [ ] Update [`language.js`](https://github.com/near/near-explorer/blob/master/frontend/src/libraries/language.js) to include Vietnamese
* [ ] Update [`moment.js`](https://github.com/near/near-explorer/blob/master/frontend/src/libraries/moment.js) for date/time format
* [ ] The Vietnamese version is deployed and tested locally to ensure all the pages, components and charts are correct
* [ ] Pull Request is submitted for Vietnamese language

# Bounty
500 USD paid NEAR

**Comment by that83** [comment]
I am interested to work on this bounty, going to take on it.

**Comment by baoanh1310** [comment]
I'm also interested to work on this bounty.

**Comment by cameron-NEAR** [comment]
Great! @that83, I officially assigned this bounty to you. When do you think you will complete it by?

**Comment by that83** [comment]
It is being reviewed in PR:
https://github.com/near/near-explorer/pull/700

**Comment by frol** [comment]
Vietnamese translation is in production! Check it out! https://explorer.near.org

**Comment by think-in-universe** [comment]
@cameron-NEAR The Vietnamese translation is in production now. We're ready to send the reward 😃

**Comment by cameron-NEAR** [comment]
Hey @that83, has this bounty been approved and paid?

**Comment by that83** [comment]
@cameron-NEAR last week I have filled in the google doc form sent by Robert but still not receive NEAR.

**Comment by dileshtanna** [comment]
Are we looking at supporting any Indian languages right now?

**Comment by andyduong1920** [comment]
Hi @think-in-universe, might I have a question, I'm curious any reason do we support Vietnamese 🤔

**Comment by that83** [comment]
I have received, please close this bounty. Thank you.

**Comment by think-in-universe** [comment]
@andyduong1920 the NEAR Vietnamese dev community is really active, and we'd like to provide the best experience for developers.

**Comment by andyduong1920** [comment]
> @andyduong1920 the NEAR Vietnamese dev community is really active, and we'd like to provide the best experience for developers.

Oh, glad to hear that @think-in-universe, thank you for your reply 🙏 💚
