### ISSUE TITLE
NEAR Explorer translation for Russian Users

### ISSUE THREAD

**Issue by think-in-universe** [near/bounties#63]
# Description
To make NEAR Explorer usable for people speaking different languages, we'd like to add i18n support for Explorer. 
In this bounty, you need to translate all English i18n strings into Russian, and add localization support such as date/time format, etc.

## Context
In the bounty https://github.com/near/bounties/issues/61, we already refactored Explorer to support i18n, and added Simplified Chinese translation. In this bounty, we'd like you to help to enhance Explorer to support Russian. 

- Explorer Frontend code repository: https://github.com/near/near-explorer/tree/master/frontend

## Skill Requirement
- JavaScript or TypeScript, React
- How i18n works in React

# Acceptance Criteria
* [x] All the following pages, are translated into Russian:
  - [x] Home: https://explorer.near.org/
  - [x] Accounts and Account Details: https://explorer.near.org/accounts and https://explorer.near.org/accounts/alice.near
  - [x] Block and Block Details: https://explorer.near.org/blocks and https://explorer.near.org/blocks/A7Zo9nAYNbfQgRbhAYg6uRYHDESH2oZk2carYczfAc2L
  - [x] Transactions and Transaction Details: https://explorer.near.org/transactions and https://explorer.near.org/transactions/7rFLj7Fp8PHW9rhr9Ye2LMHcseuGeMNtbiuq5mbbR1y6
  - [x] Nodes: https://explorer.near.org/nodes/validators
  - [x] Stats & Charts: https://explorer.near.org/stats
* [x] All the [English i18n strings](https://github.com/near/near-explorer/blob/master/frontend/src/translations/en.global.json) have a corresponding Russian version ready in the format of i18n JSON strings
* [x] Update [`language.js`](https://github.com/near/near-explorer/blob/master/frontend/src/libraries/language.js) to include Russian
* [x] Update [`moment.js`](https://github.com/near/near-explorer/blob/master/frontend/src/libraries/moment.js) for date/time format
* [x] The Russian version is deployed and tested locally to ensure all the pages, components and charts are correct
* [x] Pull Request is submitted for Russian language

# Bounty
500 USD paid NEAR

**Comment by Mish77gun** [comment]
Ready to translate into Russian
Native Russian Speaker 😉

**Comment by cameron-NEAR** [comment]
Awesome @Mish77gun! When do you think you can complete it by?

**Comment by Mish77gun** [comment]
Good day! I can submit work on August 18. Btw what will be reward for this work? 

Отправлено с iPhone

**Comment by think-in-universe** [comment]
@Mish77gun  500 USD paid in NEAR will be rewarded

**Comment by Mish77gun** [comment]
Ok, I am ready. The work will be done on September 10 and sent here (or
write another convenient way).
ср, 1 сент. 2021 г. в 13:32, think-in-universe ***@***.***>:

**Comment by gummy3426** [comment]
Hi! I'm a native speaker too and have some experience with React internalization before. If mish77gun is not going to finish the task I'm ready to complete this till 22th October.

**Comment by think-in-universe** [comment]
@nebezgreshniy yes. please. Is it able to finish it earlier? actually not much efforts are needed.  

The first valid PR for the Russian translation will be able to receive the bounty.

**Comment by Mish77gun** [comment]
> @nebezgreshniy yes. please. Is it able to finish it earlier? actually not much efforts are needed.
> 
> The first valid PR for the Russian translation will be able to receive the bounty.

My work is done, I was just waiting for your answer, in what format should I send the translation.  I will send here during the day

**Comment by think-in-universe** [comment]
@Mish77gun thanks. Please send the link of your PR here, or just mention this issue in your PR.

**Comment by Mish77gun** [comment]
> @Mish77gun thanks. Please send the link of your PR here, or just mention this issue in your PR.

Yeah, it is here : https://docs.google.com/document/d/1h65-lfzZifeE65lmQ-Y6cIfsplBNbxCbILl6zvDinmI/edit?usp=sharing

please let me know when you check it

**Comment by think-in-universe** [comment]
@Mish77gun thanks. do you mind creating a Pull Request to https://github.com/near/near-explorer/tree/master/frontend so we can preview your translation in local environment?

Please check this PR for Vietnamese if you don't know what is the expected submission: https://github.com/near/near-explorer/pull/700/files

**Comment by Mish77gun** [comment]
> @Mish77gun thanks. do you mind creating a Pull Request to https://github.com/near/near-explorer/tree/master/frontend so we can preview your translation in local environment?
> 
> Please check this PR for Vietnamese if you don't know what is the expected submission: https://github.com/near/near-explorer/pull/700/files

Yeah, no problem!  I'm new to this area and don't really understand how to do this.  Can you tell me what is required of me now?

**Comment by think-in-universe** [comment]
@Mish77gun 

similar to https://github.com/near/near-explorer/pull/700, you should be able to have a Russian version Explorer running in you local environment, and you could capture screenshot of your version and share in the PR if you'd like to. 

But the most important is that in the PR you submitted, you should have the code and JSON files ready as illustrated in the Vietnamese version.

**Comment by Mish77gun** [comment]
> But the most important is that in the PR you submitted, you should have the code and JSON files ready as illustrated in the Vietnamese version.

Before taking the job, I immediately discussed that it was not related to the technical part and was ready to perform only the translation of the site.  Which in turn I did, in the sent document there is a fully translated text + footnotes added with the original text.  Then I can no longer do anything about it: "But the most important is that in the PR you submitted, you should have the code and JSON files ready as illustrated in the Vietnamese version."

**Comment by gummy3426** [comment]
@think-in-universe 
So, as there were many errors and flaws in the file provided by Mish77gun, I've tried to complete the task asap. 
Please, review it. If any flaws will be found, I'd like to correct them.

**Comment by Mish77gun** [comment]
No problem.  But so I specifically specified in advance that I would only do the translation of the text and no more.  I've spent enough of my time and appreciate it.  The job is done, I would like to get paid.

**Comment by think-in-universe** [comment]
> Before taking the job, I immediately discussed that it was not related to the technical part and was ready to perform only the translation of the site.

> But so I specifically specified in advance that I would only do the translation of the text and no more

@Mish77gun Hey, where did you say you can only do the translation part? I didn't see that comment ...

@nebezgreshniy Are you able to submit a PR for this bounty?  Maybe you guys can work together on this bounty, and help review the translation together.

**Comment by Mish77gun** [comment]
@think-in-universe 
My first comment “ Ready to translate into Russian
Native Russian Speaker 😉”

And also I was asking about reward bcs I would like only to translate. And u answered 500usd. Can I get money for my work?

**Comment by think-in-universe** [comment]
> My first comment “ Ready to translate into Russian
> Native Russian Speaker 😉”

It doesn't mean translation is enough, though translation is an essential part. 
The **Acceptance Criteria** section has clearly described what you need to do actually. 


> And also I was asking about reward bcs I would like only to translate. And u answered 500usd. Can I get money for my work?

sorry. you can't, unless your submission satisfies all the **Acceptance Criteria**.

**Comment by Mish77gun** [comment]
> > My first comment “ Ready to translate into Russian
> > Native Russian Speaker 😉”
> 
> It doesn't mean translation is enough, though translation is an essential part.
> The **Acceptance Criteria** section has clearly described what you need to do actually.
> 
> > And also I was asking about reward bcs I would like only to translate. And u answered 500usd. Can I get money for my work?
> 
> sorry. you can't, unless your submission satisfies all the **Acceptance Criteria**.

It means that we did not understand each other.  This does not change the essence of the matter, I have nothing to do with JS and I cannot do anything more than translation.  Can I get a partial payment?

**Comment by think-in-universe** [comment]
@Mish77gun if you can collaborate with someone to help submit a PR based on your translation, you guys can divide the bounty based on your contribution.

**Comment by nebezgreshniy** [comment]
@think-in-universe Sorry, I've made it here 11 hours ago based on my own translation. 
[https://github.com/near/near-explorer/pull/738](url)

**Comment by nebezgreshniy** [comment]
[https://github.com/near/near-explorer/pull/738](url)

**Comment by gummy3426** [comment]
@think-in-universe
I've made it [here](https://github.com/near/near-explorer/pull/738) 11 hours ago based on my own translation.

**Comment by Mish77gun** [comment]
@think-in-universe 

A colleague did the job too.  My job is also done, there is to follow your checklist with the task of translating the text, that's half the job.  My time is not free and I appreciate it.  I want to get my own, albeit small, but reward.

**Comment by think-in-universe** [comment]
@Mish77gun could you please help review the translation in this PR? https://github.com/near/near-explorer/pull/738  if so, you guys can split the bounty if @nebezgreshniy is also OK with this.

**Comment by dec0dOS** [comment]
Hello, @think-in-universe!
I've faced by the accident to this tread and want to help to resolve the conflict.
As a native Russian speaker and a long-term NEAR user, I don't think that @Mish77gun does deserve any bounty, he does not understand the domain-specific terms so the translation is useless. Also, @Mish77gun promised to complete the task about 2 times but didn't on time. 
If you need another person to review the @nebezgreshniy work, I could help without any claim to the reward.

**Comment by Mish77gun** [comment]
@think-in-universe 

Yes, maybe a mistake on my part.  But nevertheless, I spent my time doing this work.  I would like to receive the minimum reward for my work -> mish77gun.near 
I don’t see any point in communicating further, since my colleague has already done the work himself.  I rate it excellently.

**Comment by think-in-universe** [comment]
> Yes, maybe a mistake on my part. But nevertheless, I spent my time doing this work. I would like to receive the minimum reward for my work -> mish77gun.near
> I don’t see any point in communicating further, since my colleague has already done the work himself. I rate it excellently.

@Mish77gun  the bounty will be rewarded based on the result and quality of the work, not the time you spent. 
who is your colleague? do you mean @nebezgreshniy ?

**Comment by Mish77gun** [comment]
> > Yes, maybe a mistake on my part. But nevertheless, I spent my time doing this work. I would like to receive the minimum reward for my work -> mish77gun.near
> > I don’t see any point in communicating further, since my colleague has already done the work himself. I rate it excellently.
> 
> @Mish77gun the bounty will be rewarded based on the result and quality of the work, not the time you spent.
> who is your colleague? do you mean @nebezgreshniy ?

Guys, this is wrong.  Every job must be paid.  Have a nice day everyone, I will not come back here again!

**Comment by think-in-universe** [comment]
@dec0dOS thanks for your comments. I'm not sure about the quality of translation since I cannot read Russian. We need developers from Russian community to help review. 

Please feel free to review the PR if you have any suggestions or comments: https://github.com/near/near-explorer/pull/738

**Comment by think-in-universe** [comment]
@Mish77gun 

I think you didn't notice the requirement since the bounty has stated its **Skill Requirement** clearly.

> JavaScript or TypeScript, React
> How i18n works in React

Thanks for your contribution. But I'm sorry we have to reward the bounties based on the actual delivery that meets the **Acceptance Criteria**. As said earlier:

> The first valid PR for the Russian translation will be able to receive the bounty.

**Comment by dec0dOS** [comment]
@think-in-universe, I've made some changes to the translation and @nebezgreshniy has already approved the PR. It seems to be looking good now!

**Comment by frol** [comment]
@think-in-universe reading the Russian translations I fear that our Chinese and Vietnamese translations might also be misleading. While it might be a good starting point, I believe we might want to keep English translation around and a call-to-action button to improve translation or take a proactive move and ask people to validate the work.

**Comment by think-in-universe** [comment]
@frol thanks Frol. 

For Chinese and Vietnamese translation, I'm sure they are in quite high quality since some developers with proved NEAR-related translation records have helped to translate and review. Also at least for the Chinese version, I received feedback from developers comment that the translation was done quite well, though it's still possible some terms' translation can be challenged or improved. 

But yeah, we can leave a button there for collecting feedback / creating issues in case users want to report any misleading translation.

**Comment by frol** [comment]
Russian translation has been completed, merged, and deployed to production! :tada: 

https://github.com/near/near-explorer/pull/762

@nebezgreshniy Thanks for your contribution!

@think-in-universe Please, follow up on the bounty pay :pray:

**Comment by gummy3426** [comment]
@think-in-universe The task is already completed. Great thanks for the opportunity to contribute to the project.

**Comment by think-in-universe** [comment]
@nebezgreshniy cool. thanks a lot for your contribution. 

Could you please share your telegram or discord handle? so we can follow up with the bounty payout.

**Comment by gummy3426** [comment]
@think-in-universe
telegram: @nebezgreshnaYA

**Comment by frol** [comment]
@think-in-universe Was this bounty paid out? Should we close this issue?

**Comment by think-in-universe** [comment]
@frol yes. the bounty has been paid.
