### ISSUE TITLE
Transfer and payment using a bot

### ISSUE THREAD

**Issue by vorsik22** [near/bounties#68]
# Description
Allowed API for automating users, connected to the Discord bot, allowing transferring to another person reliably and conveniently, you just need to log into the Near bot's Discord!
## Context
Deterministically connect a bot with a Discord user with a personal access key issued in the Near personal account, link once and then all access will be available through the Discord bot, which can be paused in the Near personal account, if necessary!
All financial services will be much more convenient.

# Acceptance Criteria
My idea:
- open an account with Near accumulation under% for several months. This will increase more user engagement and interest.
- by connecting a bot, you can easily make a transfer to a close or partner just with the help of the Near bot Discord
- Initialize accounts with minimum balance to create NEAR account ID with Near Bot Discord, which can only happen once with OAuth login quickly and easily. Even through a mobile phone with Discord installed on the device

# Bounty
[$5,000 USD in NEAR]

**Comment by poznyakbogdan** [comment]
Hello guys! Is there an opportunity to work on this issue?

**Comment by cameron-NEAR** [comment]
This has already been completed - https://github.com/bafnetwork/baf-wallet-v2
