### ISSUE TITLE
i18n support of Paras

### ISSUE THREAD

**Issue by think-in-universe** [near/bounties#69]
# Description
Paras is a great NFT market project built with NEAR. 

As Paras community grows globally, it's important for https://paras.id/ to support multiple languages, including Chinese, Korean, Vietnamese, Russian, Spanish, French, etc. 

To enable the multi-language feature, we need to refactor the frontend source code https://github.com/ParasHQ/paras-landing/tree/v2 (v2 branch) , and make it easy to translate strings with i18n JSON strings. 

## Context
Paras' user interface now only supports English. With more communities joining, it's important to provide UI in native languages for users from different countries and regions. 

![image](https://user-images.githubusercontent.com/46699230/133728413-be5e757a-cdc8-4356-99af-56367b415c3b.png)

# Acceptance Criteria
* [ ] one appropriate NPM package is used to enable i18n support in the current Next.js based app
* [ ] all the major pages in https://paras.id are translated 
* [ ] all English strings are merged into a single JSON file
* [ ] a JSON file for Chinese is created to demo how the i18n feature works, with most of the strings translated into Chinese (you don't need to translate all if you have questions about some of the terms). 
* [ ] a language selector is added, with dropdown items English and Chinese, and works well in both Web and Mobile view

# Bounty
$600 paid in NEAR

**Comment by JuEnPeHa** [comment]
Hi, I could work with this if it was Spanish instead of Chinese.

I guess I'll wait for an upcoming issue, have a great day.

Juan Enrique

**Comment by wuxiangwu** [comment]
Hi , I'm a FrontEnd Developer, I can do it!

**Comment by think-in-universe** [comment]
@JuEnPeHa thanks for your interest. Chinese is preferred at least in this bounty. Paras team might also need your help to add Spanish UI later, after the i18n support is enabled. Please stay tuned.

@wuxiangwu thanks. please submit a PR to https://github.com/ParasHQ/paras-landing/tree/v2 to complete the bounty.  when do you think you'll be able to complete the bounty?

**Comment by cryptovaibhav** [comment]
@think-in-universe  Hi, I am a full stack developer. I can work on the infrastructure part and make it globalized. We can discuss more if you are interested. However, the for chinese translations, I would have to rely on Google translate.

**Comment by AlexDenver** [comment]
@think-in-universe have raised a PR ([#131](https://github.com/ParasHQ/paras-landing/pull/131/files)) with one of the pages localized so that I can get ample feedback before I make the changes across the repo.

**Comment by wuxiangwu** [comment]
@Robert Yan   Sorry, I Just see the question. I have done!, and will Pull Request!

**Comment by 0xslipk** [comment]
> @JuEnPeHa thanks for your interest. Chinese is preferred at least in this bounty. Paras team might also need your help to add Spanish UI later, after the i18n support is enabled. Please stay tuned.
> 
> @wuxiangwu thanks. please submit a PR to https://github.com/ParasHQ/paras-landing/tree/v2 to complete the bounty. when do you think you'll be able to complete the bounty?

I can help you with the Spanish UI. send a me a direct message on [twitter](https://twitter.com/jarcodallo) :D

**Comment by tranquang9a1** [comment]
I can support to translate to Vietnamese. Contact me if you need help

**Comment by think-in-universe** [comment]
thanks to @wuxiangwu 's contribution: https://github.com/ParasHQ/paras-landing/pull/135. the i18n support is already launched in production: https://paras.id

**Comment by think-in-universe** [comment]
@jarcodallo and @tranquang9a1 thanks for your interest. 

do you mind sharing your telegram account? so you can join the discussion with Paras team.

**Comment by 0xslipk** [comment]
> @jarcodallo and @tranquang9a1 thanks for your interest.
> 
> do you mind sharing your telegram account? so you can join the discussion with Paras team.

Hey, my telegram is `jarcodallo` 😄

**Comment by JuEnPeHa** [comment]
> @jarcodallo and @tranquang9a1 thanks for your interest.
> 
> do you mind sharing your telegram account? so you can join the discussion with Paras team.

Hello, good morning, I was the first that offered you Spanish @JuanEnriquePH

**Comment by tranquang9a1** [comment]
> @jarcodallo and @tranquang9a1 thanks for your interest.
> 
> do you mind sharing your telegram account? so you can join the discussion with Paras team.

My telegram account is same with github: tranquang9a1

**Comment by think-in-universe** [comment]
cool. thanks everyone @jarcodallo @JuEnPeHa @tranquang9a1

**Comment by unlimited2989** [comment]
@think-in-universe let me know if you still need help with Vietnamese translation. Got some experience to do translation for a few big enterprises software rollout. Thank you.

**Comment by think-in-universe** [comment]
@unlimited2989 thanks. please leave your telegram handle here, and Paras team will contact you if they need your help.

**Comment by unlimited2989** [comment]
> @unlimited2989 thanks. please leave your telegram handle here, and Paras team will contact you if they need your help.

Tks. My Telegram @MrRyu298

**Comment by OZ20** [comment]
By any chance if Bahasa Melayu is needed, you can contact me @OZ20DEV (telegram). Thanks!

**Comment by rikijug2** [comment]
if it needs to be translated to Croatian or any Balkan language hit me up tele @rikijug22

**Comment by Fifiboss98** [comment]
I'm available for French translation

My Telegram handle Fideledossou

**Comment by Seva98** [comment]
For Czech translation hit me on telegram @sevcik_dev

**Comment by cuongdcdev** [comment]
Hello @think-in-universe , I can help with Vietnamese translation, my tg is @cuongdcc

**Comment by JoseGabriel-web** [comment]
I can translate it to Spanish will create the JSON file with the translations.

You guys can also contact me here: https://twitter.com/nearmemes_

**Comment by think-in-universe** [comment]
thanks everyone. I think Paras team will reach out if they need your help. 😃

**Comment by JuEnPeHa** [comment]
> cool. thanks everyone @jarcodallo @JuEnPeHa @tranquang9a1

Spanish translation created in October 8th.
https://github.com/ParasHQ/paras-landing/pull/141

And edited in order to work in the new version of the JSON file in November 22th.
https://github.com/ParasHQ/paras-landing/commit/f08c8218b822cc5304a7ea96ddc913ca5d194730

https://paras.id/es

Happy to help the community, have a great day :)
