### ISSUE TITLE
Exhaustively document the Rust JSON RPC Client

### ISSUE THREAD

**Issue by miraclx** [near/bounties#77]
> This bounty has been claimed. Awardee: @iTranscend

# Description

- Exhaustively document all types and structures in the [near-jsonrpc-client](https://github.com/near/near-jsonrpc-client-rs) crate.
- Documentation of RPC methods can be pulled from the official documentation. https://docs.near.org/docs/api/rpc
- Add useful snippets of code showing examples in each of the [RPC methods](https://docs.rs/near-jsonrpc-client/0.3.0/near_jsonrpc_client/methods/index.html) to help users get started.
- And in the case of the `query` method, include examples highlighting [all the query requests](https://github.com/near/nearcore/blob/6a0349f31a6b681e825ae98015d0d842d54fd21c/core/primitives/src/views.rs#L267).

## Context

`near-jsonrpc-client` could be better documented and the addition of helpful snippets of code showing usage for each RPC method would help users get started quickly, allowing for a better experience overall.

See https://github.com/near/near-jsonrpc-client-rs/issues/37

# Acceptance Criteria

* [x] All RPC method modules must be documented, with examples.
* [x] Documentation must be simple to parse through, easy to find relevant information and straightforward to understand.
* [x] All the code examples must be concise (showing relevant bits), as well as being successfully compilable and testable.

# Bounty

200 NEAR

**Comment by iTranscend** [comment]
Hey @miraclx, I'd like to take up this bounty

**Comment by miraclx** [comment]
@iTranscend, sounds good, I'll assign you.

Do you have an idea of when you will have something we can look at?

**Comment by iTranscend** [comment]
> @iTranscend, sounds good, I'll assign you.
> 
> Do you have an idea of when you will have something we can look at?

I should have the tasks completed in two weeks from now

**Comment by miraclx** [comment]
Sounds good. I'll follow up soon to discuss progress. Feel free to ask any questions you may have in here.

**Comment by mfornet** [comment]
It is not part of the issue, but it will be really nice, if as a result of this issue we could also get a postman exportable version of the RPC: See one from [Ethereum](https://www.postman.com/3pdYxK6SJYrr71/workspace/blok-z-s-public-workspace/request/6710670-5b6629db-128e-4066-b6cb-840f6e7952e3) for more details.

**Comment by miraclx** [comment]
Yeah, that's a great idea. It's out of scope for this bounty as it's defined, but I'll keep a note of this and have this set up soon.

**Comment by ankitzm** [comment]
Is this bounty still open? Have recently built a Dapp on Near, it's awesome. Ready to work on this bounty.

**Comment by miraclx** [comment]
@ankitzm, yes it's still open, although @iTranscend has been working on it for a while now and it is almost complete.

https://github.com/near/near-jsonrpc-client-rs/issues/51

**Comment by ankitzm** [comment]
Great work @iTranscend. Is there anything I can help with.

**Comment by iTranscend** [comment]
It’s very kind of you to offer to help @ankitzm, but there's currently no task that I haven't opened a PR for.
Thanks.

**Comment by uplaw** [comment]
@miraclx Is this task still available ?

**Comment by miraclx** [comment]
@uplaw This bounty is complete, and the reward has been claimed.

Thanks for checking in.
