### ISSUE TITLE
Pool Together delegation | Bounty: 2000 NEAR

### ISSUE THREAD

**Issue by ilblackdragon** [near/bounties#8]
# Description
Use idea of PoolTogether with delegation rewards.
Create a smart contract that users can delegate to.
All delegations then are re-delegated to one of the smart contract pools.
Every X blocks (can be 12h, day or week), a lottery will be run weighted by how much coins they delegated and one of delegators will win all rewards from everyone.

## Context
PoolTogether is a way to pool together funds and win lending rewards: https://www.pooltogether.com/

# Acceptance
* [ ] A contract that would accept deposits and delegate them to one or many pools
* [ ] Simple UI that can be logged in with NEAR Wallet and deposit funds / see winnings.

# Bounty
2000 $NEAR

**Comment by zavodil** [comment]
Shall we consider number of seats? Can user with 1 NEAR stake win all rewards?

**Comment by ilblackdragon** [comment]
@zavodil Sure, it should be weighted by how much they deposited into contracts.

**Comment by andytcf** [comment]
Is this one still ongoing? Is there any additional details and requirements that haven't been included as this issue was opened a while back? 

Thanks

**Comment by aj07** [comment]
Is this bounty still Open ?

**Comment by ilblackdragon** [comment]
Yes, this bounty is still open. 
If anyone wants to work on it - please post progress here for everyone to see.

**Comment by ouromoros** [comment]
I'm interested in working on this. My draft smart contract have the following change methods:

*stake*: transfer some amount of NEAR to the protocol account which it will delgate to speicific pool
*evaluate*: evaluate (calculate lottery winner) and update the balance(staked + reward) of all staked users, this function should be called by party of interest in a timely manner, and possibly be rewarded to incentivise
*unstake*: unstake some amount of NEAR that's staked in the pool
*withdraw*: withdraw the amount of NEAR that's unstaked three epochs ago

The contract should store and manage records of corresponding balance of each participant. One problem is how do we make sure `evaluate` is called every epoch? If there isn't some built-in mechanism in NEAR to implement it, then we'll have to deal with the special condition when `evaluate` is not called and multiple epochs have passed.

I'm fairly new to NEAR contract programming, I would appreciate some suggestions.

**Comment by gagdiez** [comment]
With @lunafromthemoon we have created Pool Party! You can see its first version running in the testnet in the following link: https://siasky.net/hns/poolap/.

**How does it work?**
The pool is completely functional. Users can stake, unstake, and withdraw their NEAR, and at most once per day the interest generated is raffled between the participants.
- When the money is staked, we transfer it to another pool (see https://wallet.testnet.near.org/profile/dev-1613329875464-2956818) and credit the user with "tickets". The user gets the same amount of tickets than NEAR it staked. 
- When the user unstakes the tickets, we unstake the money back from the 3rd party pool, and 3 days after, we allow the user to withdraw the NEAR, which is in turn withdraw from the 3rd party pool.
- Once per day (we are using a short time to test our front end, we plan to increase it to once per week) we call the method "raffle" in the contract. It then randomly selects a user to give all the accumulated interest of the day. The "raffle" algorithm is **fair**, and takes into account the weight of each user. If you have S tickets out of T tickets, then your probability of winning on each raffle is S/T.

We have performed exhausting testing on the smart contract, and found no way to leave the money stalled or locked in the pool. Furthermore, we tested our raffle algorithm, and it is highly performant, allowing us to handle thousands of subjects without running out of gas.

**What are the next steps?**
- Finishing testing the front end, there are probably some small fixes to be made.
- Extend the website with more information about how Pool Party works
- Get a "normal" URL
- Change raffle time
- Publish it in mainnet, and most probably add a minimum fixed prize (something that we could cover ourselves) to attract users.

@ilblackdragon is our current status enough to claim the bounty? Or would something else be needed?

**Comment by ilblackdragon** [comment]
Looks great! I think the current state is good to claim the bounty.
How about you add your near account to Github description to facilitate payment?

**Comment by gagdiez** [comment]
@ilblackdragon Great news! I have updated my profile with my near wallet: gagdiez.near

**Comment by ilblackdragon** [comment]
@gagdiez can link to the source code here and I'll close it.

**Comment by gagdiez** [comment]
The source code is in: https://github.com/gagdiez/pool_party

We will work on adding more information to the README.md soon.

We have received the bounty. Thank you @ilblackdragon.

We will get in contact soon with the NEAR community to inform the launch in mainnet.
